import { Activity, FileImage, Gauge, MapIcon, ShieldAlert, Sparkles, User2, Variable, Zap } from 'lucide-react';

export const adminDestinations = [
  {
    name: 'Users',
    to: '/admin/users',
    Icon: User2,
    bgColor: 'bg-green-500',
    hoverBg: 'hover:bg-green-600',
    description: 'Manage all users of the platform',
  },
  {
    name: 'Tasks',
    to: '/admin/tasks',
    Icon: Zap,
    bgColor: 'bg-yellow-500',
    hoverBg: 'hover:bg-yellow-600',
    description: 'Track, assign, and complete tasks',
  },
  {
    name: 'Templates',
    to: '/admin/templates',
    Icon: FileImage,
    bgColor: 'bg-blue-500',
    hoverBg: 'hover:bg-blue-600',
    description: 'Manage image generation templates',
  },
  {
    name: 'Global Variables',
    to: '/admin/global-variables',
    Icon: Variable,
    bgColor: 'bg-teal-500',
    hoverBg: 'hover:bg-teal-600',
    description: 'Shared variables used across templates',
  },
  {
    name: 'Models',
    to: '/admin/models',
    Icon: Sparkles,
    bgColor: 'bg-pink-500',
    hoverBg: 'hover:bg-pink-600',
    description: 'Configure AI generation models',
  },
  {
    name: 'Audits',
    to: '/admin/audit',
    Icon: MapIcon,
    bgColor: 'bg-purple-500',
    hoverBg: 'hover:bg-purple-600',
    description: 'Review audit logs and system events',
  },
  {
    name: 'Trust',
    to: '/admin/moderation',
    Icon: ShieldAlert,
    bgColor: 'bg-red-500',
    hoverBg: 'hover:bg-red-600',
    description: 'Review quarantined uploads and denylisted hashes',
  },
  {
    name: 'Egress',
    to: '/admin/egress',
    Icon: Gauge,
    bgColor: 'bg-cyan-600',
    hoverBg: 'hover:bg-cyan-700',
    description: 'Inspect delivery bandwidth consumers',
  },
  {
    name: 'Activity',
    to: '/admin/tasks/logs',
    Icon: Activity,
    bgColor: 'bg-slate-600',
    hoverBg: 'hover:bg-slate-700',
    description: 'Inspect recent task execution history',
  },
] as const;
