declare const styles: {
  readonly "content": string;
  readonly "contentAspect": string;
  readonly "contentInner": string;
  readonly "day": string;
  readonly "dayEmpty": string;
  readonly "dayGrid": string;
  readonly "dayNumber": string;
  readonly "event": string;
  readonly "eventBar": string;
  readonly "eventBarArrow": string;
  readonly "eventLanes": string;
  readonly "eventTitle": string;
  readonly "lane": string;
  readonly "nav": string;
  readonly "navIcon": string;
  readonly "navTitle": string;
  readonly "navToday": string;
  readonly "overflowCellEmpty": string;
  readonly "overflowDialogDay": string;
  readonly "overflowDialogLabel": string;
  readonly "overflowDialogTitle": string;
  readonly "overflowItem": string;
  readonly "overflowItemColor": string;
  readonly "overflowItemContent": string;
  readonly "overflowItemDate": string;
  readonly "overflowItemTitle": string;
  readonly "overflowList": string;
  readonly "overflowRow": string;
  readonly "overflowScrollArea": string;
  readonly "overflowTrigger": string;
  readonly "root": string;
  readonly "weekRow": string;
  readonly "weekday": string;
  readonly "weekdays": string;
};
export = styles;

